const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    GET_ALL_CODE_START: 'GET_ALL_CODE_START',
    GET_ALL_CODE_SUCCESS: ' GET_ALL_CODE_SUCCESS',
    GET_ALL_CODE_END: 'GET_ALL_CODE_END',
    ADD_NEW_USER: ' ADD_NEW_USER',
    ADD_NEW_USER_SUCCESS: 'ADD_NEW_USER_SUCCESS',
    ADD_NEW_USER_FAIL: 'ADD_NEW_USER_FAIL',

    CREATE_USER_SUCCESS: ' CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: ' CREATE_USER_FAIL',

    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAIL: 'GET_ALL_USERS_FAIL',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAIL: 'EDIT_USER_FAIL',

    GET_DOCTOR_SUCCESS: 'GET_DOCTOR_SUCCESS',
    GET_DOCTOR_FAIL: 'GET_DOCTOR_FAIL'
})

export default actionTypes;